package Loan.Loanmodel.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.domain.DBSequence;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Apr 21 13:10:02 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LoanRequestVORowImpl extends ViewRowImpl {
    public static final int ENTITY_LOANREQUESTEO = 0;
    public static final int ENTITY_POLICE_PERSON = 1;
    public static final int ENTITY_POLICE_PERSON1 = 2;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Id,
        Loaner,
        Namenp,
        FatherName,
        GrandFatherName,
        Address,
        Accountno,
        Mobileno,
        Email,
        Moj,
        Mor,
        Code,
        Position,
        CurrentUnit,
        NpDate,
        EnDate,
        Principal,
        Rate,
        Status,
        Remarks,
        Aprovedby,
        Namenp1,
        Code1,
        Position1,
        CurrentUnit1,
        Createdby,
        Createdon,
        Status2,
        AppModule_PolicePersonLov1_1,
        AppModule_RankLov1_1,
        AppModule_PolicePersonLov1_2,
        PolicePersonLov1,
        ApprovalStatusLOV1,
        PolicePersonLov2;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ID = AttributesEnum.Id.index();
    public static final int LOANER = AttributesEnum.Loaner.index();
    public static final int NAMENP = AttributesEnum.Namenp.index();
    public static final int FATHERNAME = AttributesEnum.FatherName.index();
    public static final int GRANDFATHERNAME = AttributesEnum.GrandFatherName.index();
    public static final int ADDRESS = AttributesEnum.Address.index();
    public static final int ACCOUNTNO = AttributesEnum.Accountno.index();
    public static final int MOBILENO = AttributesEnum.Mobileno.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int MOJ = AttributesEnum.Moj.index();
    public static final int MOR = AttributesEnum.Mor.index();
    public static final int CODE = AttributesEnum.Code.index();
    public static final int POSITION = AttributesEnum.Position.index();
    public static final int CURRENTUNIT = AttributesEnum.CurrentUnit.index();
    public static final int NPDATE = AttributesEnum.NpDate.index();
    public static final int ENDATE = AttributesEnum.EnDate.index();
    public static final int PRINCIPAL = AttributesEnum.Principal.index();
    public static final int RATE = AttributesEnum.Rate.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int APROVEDBY = AttributesEnum.Aprovedby.index();
    public static final int NAMENP1 = AttributesEnum.Namenp1.index();
    public static final int CODE1 = AttributesEnum.Code1.index();
    public static final int POSITION1 = AttributesEnum.Position1.index();
    public static final int CURRENTUNIT1 = AttributesEnum.CurrentUnit1.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int CREATEDON = AttributesEnum.Createdon.index();
    public static final int STATUS2 = AttributesEnum.Status2.index();
    public static final int APPMODULE_POLICEPERSONLOV1_1 = AttributesEnum.AppModule_PolicePersonLov1_1.index();
    public static final int APPMODULE_RANKLOV1_1 = AttributesEnum.AppModule_RankLov1_1.index();
    public static final int APPMODULE_POLICEPERSONLOV1_2 = AttributesEnum.AppModule_PolicePersonLov1_2.index();
    public static final int POLICEPERSONLOV1 = AttributesEnum.PolicePersonLov1.index();
    public static final int APPROVALSTATUSLOV1 = AttributesEnum.ApprovalStatusLOV1.index();
    public static final int POLICEPERSONLOV2 = AttributesEnum.PolicePersonLov2.index();

    /**
     * This is the default constructor (do not remove).
     */
    public LoanRequestVORowImpl() {
    }
}

