package Loan.Loanmodel.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 05 13:43:23 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LoanApprovalRVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public LoanApprovalRVOImpl() {
    }
}

