package Loan.Loanmodel.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 05 13:43:23 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LoanApprovalRVORowImpl extends ViewRowImpl {

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Id,
        Loaner,
        Namenp,
        Code,
        Position,
        CurrentUnit,
        Accountno,
        Approveddate,
        Emi,
        Moj,
        Mor,
        NpDate,
        EnDate,
        Principal,
        Rate,
        Status,
        Remarks,
        Aprovedby,
        Namenp1,
        Code1,
        Position1,
        CurrentUnit1,
        Createdby,
        Createdon,
        PolicePersonLov1,
        RankLov1,
        ApprovalStatusLOV1;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ID = AttributesEnum.Id.index();
    public static final int LOANER = AttributesEnum.Loaner.index();
    public static final int NAMENP = AttributesEnum.Namenp.index();
    public static final int CODE = AttributesEnum.Code.index();
    public static final int POSITION = AttributesEnum.Position.index();
    public static final int CURRENTUNIT = AttributesEnum.CurrentUnit.index();
    public static final int ACCOUNTNO = AttributesEnum.Accountno.index();
    public static final int APPROVEDDATE = AttributesEnum.Approveddate.index();
    public static final int EMI = AttributesEnum.Emi.index();
    public static final int MOJ = AttributesEnum.Moj.index();
    public static final int MOR = AttributesEnum.Mor.index();
    public static final int NPDATE = AttributesEnum.NpDate.index();
    public static final int ENDATE = AttributesEnum.EnDate.index();
    public static final int PRINCIPAL = AttributesEnum.Principal.index();
    public static final int RATE = AttributesEnum.Rate.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int APROVEDBY = AttributesEnum.Aprovedby.index();
    public static final int NAMENP1 = AttributesEnum.Namenp1.index();
    public static final int CODE1 = AttributesEnum.Code1.index();
    public static final int POSITION1 = AttributesEnum.Position1.index();
    public static final int CURRENTUNIT1 = AttributesEnum.CurrentUnit1.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int CREATEDON = AttributesEnum.Createdon.index();
    public static final int POLICEPERSONLOV1 = AttributesEnum.PolicePersonLov1.index();
    public static final int RANKLOV1 = AttributesEnum.RankLov1.index();
    public static final int APPROVALSTATUSLOV1 = AttributesEnum.ApprovalStatusLOV1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public LoanApprovalRVORowImpl() {
    }
}

