package Loan.Loanmodel.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Apr 21 13:10:02 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LoanRequestVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public LoanRequestVOImpl() {
    }
}

