package Loan.Loanmodel.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.domain.DBSequence;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 29 14:36:49 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PersonLoanVORowImpl extends ViewRowImpl {
    public static final int ENTITY_LOANREQUESTEO = 0;
    public static final int ENTITY_PERSONEO = 1;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Loaner,
        Id,
        Name,
        Code,
        CurrentUnit,
        FatherName,
        GrandFatherName,
        Position,
        Rnk,
        Moj,
        Mor,
        JobStatus,
        NpDate,
        Principal,
        Rate,
        Remarks,
        Aprovedby,
        Status,
        Createdby,
        Createdon;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int LOANER = AttributesEnum.Loaner.index();
    public static final int ID = AttributesEnum.Id.index();
    public static final int NAME = AttributesEnum.Name.index();
    public static final int CODE = AttributesEnum.Code.index();
    public static final int CURRENTUNIT = AttributesEnum.CurrentUnit.index();
    public static final int FATHERNAME = AttributesEnum.FatherName.index();
    public static final int GRANDFATHERNAME = AttributesEnum.GrandFatherName.index();
    public static final int POSITION = AttributesEnum.Position.index();
    public static final int RNK = AttributesEnum.Rnk.index();
    public static final int MOJ = AttributesEnum.Moj.index();
    public static final int MOR = AttributesEnum.Mor.index();
    public static final int JOBSTATUS = AttributesEnum.JobStatus.index();
    public static final int NPDATE = AttributesEnum.NpDate.index();
    public static final int PRINCIPAL = AttributesEnum.Principal.index();
    public static final int RATE = AttributesEnum.Rate.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int APROVEDBY = AttributesEnum.Aprovedby.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int CREATEDON = AttributesEnum.Createdon.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PersonLoanVORowImpl() {
    }
}

