package Loan.Loanmodel.vo;

import Loan.Loanmodel.vo.common.PersonPhone;

import oracle.jbo.Row;
import oracle.jbo.server.Entity;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Apr 21 11:32:56 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PersonPhoneImpl extends ViewObjectImpl implements PersonPhone {
    /**
     * This is the default constructor (do not remove).
     */
    public PersonPhoneImpl() {
    }
    
    public String getRowStatus(Row row){
     PersonPhoneRowImpl rwImpl = (PersonPhoneRowImpl)row;
     String rwStatus =
     translateStatusToString(rwImpl.getEntity(0).getEntityState());
     return rwStatus;
    }
    private String translateStatusToString(byte b) {
     String ret = null;
     switch (b) {
     case Entity.STATUS_INITIALIZED: {
     ret = "Initialized";
     break;
     }
     case Entity.STATUS_MODIFIED: {
     ret = "Modified";
     break;
     }
     case Entity.STATUS_UNMODIFIED: {
     ret = "Unmodified";
     break;
     }
     case Entity.STATUS_NEW: {
     ret = "New";
     break;
     }
     }
    return ret;
    }

    
    
    
    
}

