package Loan.Loanmodel.vo;

import java.sql.Timestamp;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Apr 21 11:32:56 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PersonPhoneRowImpl extends ViewRowImpl {
    public static final int ENTITY_PHONEBOOK = 0;
    public static final int ENTITY_POLICE_PERSON = 1;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Computercode,
        Code,
        Position,
        Namenp,
        Name,
        CurrentUnit,
        Accountno,
        Mobileno,
        Email,
        Createdby,
        Createon,
        PolicePersonLov1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int COMPUTERCODE = AttributesEnum.Computercode.index();
    public static final int CODE = AttributesEnum.Code.index();
    public static final int POSITION = AttributesEnum.Position.index();
    public static final int NAMENP = AttributesEnum.Namenp.index();
    public static final int NAME = AttributesEnum.Name.index();
    public static final int CURRENTUNIT = AttributesEnum.CurrentUnit.index();
    public static final int ACCOUNTNO = AttributesEnum.Accountno.index();
    public static final int MOBILENO = AttributesEnum.Mobileno.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int CREATEON = AttributesEnum.Createon.index();
    public static final int POLICEPERSONLOV1 = AttributesEnum.PolicePersonLov1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PersonPhoneRowImpl() {
    }
}

