package Loan.Loanmodel.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 05 10:17:10 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ShowUserLovImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ShowUserLovImpl() {
    }
}

