package Loan.Loanmodel.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Dec 21 10:22:01 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UserLovImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public UserLovImpl() {
    }
}

