package Loan.Loanmodel.vo.common;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Row;
import oracle.jbo.domain.DBSequence;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 04 17:11:02 IST 2019
// ---------------------------------------------------------------------
public interface LoanApprovalVORow extends Row {
    String getLoaner();

    void setLoaner(String value);

    DBSequence getId();

    void setId(DBSequence value);

    String getName();

    String getCode();

    String getNamenp();

    String getPosition();

    String getPositionen();

    String getCurrentUnit();

    String getAccountno();

    String getMobileno();

    String getEmail();

    String getFatherName();

    String getGrandFatherName();

    String getMoj();

    String getMor();

    String getNpDate();

    void setNpDate(String value);

    Timestamp getEnDate();

    void setEnDate(Timestamp value);

    Integer getPrincipal();

    void setPrincipal(Integer value);

    BigDecimal getRate();

    void setRate(BigDecimal value);

    String getRemarks();

    void setRemarks(String value);

    Integer getStatus();

    void setStatus(Integer value);

    String getAprovedby();

    void setAprovedby(String value);

    String getName1();

    String getCode1();

    String getNamenp1();

    String getPosition1();

    String getPositionen1();

    String getCurrentUnit1();

    String getCreatedby();

    Timestamp getCreatedon();

    String getStatus2();

    String getshowUser();

}

