package Loan.Loanmodel.vo.common;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Row;
import oracle.jbo.domain.DBSequence;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 29 14:49:48 IST 2018
// ---------------------------------------------------------------------
public interface PersonLoanVORow extends Row {
    String getLoaner();

    void setLoaner(String value);

    DBSequence getId();

    void setId(DBSequence value);

    String getName();

    String getCode();

    String getCurrentUnit();

    String getFatherName();

    String getGrandFatherName();

    String getPosition();

    String getRnk();

    String getMoj();

    String getMor();

    String getJobStatus();

    String getNpDate();

    void setNpDate(String value);

    BigDecimal getPrincipal();

    void setPrincipal(BigDecimal value);

    BigDecimal getRate();

    void setRate(BigDecimal value);

    String getRemarks();

    void setRemarks(String value);

    String getAprovedby();

    void setAprovedby(String value);

    Integer getStatus();

    void setStatus(Integer value);

    String getCreatedby();

    Timestamp getCreatedon();
}

