package Loan.Loanmodel.vo.common;

import oracle.jbo.Row;
import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Apr 21 11:36:54 IST 2019
// ---------------------------------------------------------------------
public interface PersonPhone extends ViewObject {
    String getRowStatus(Row row);
}

